# Generated by Django 4.2 on 2023-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Renk Kodu'),
        ),
    ]
