# Generated by Django 4.2 on 2023-11-11 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProduct', '0002_color_title_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('like', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='Beğenen Kullanıcı')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProduct.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
